name = "remix-cloudflare-workers"
compatibility_date = "2022-05-28"
compatibility_flags = ["durable_object_fetch_allows_relative_url"]
main = "./dist/worker.mjs"
workers_dev = true

[site]
bucket = "./public"

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
# This is a deprecated config, but nessessary for miniflare.
format = "modules"

[durable_objects]
bindings = [{ name = "COUNTER", class_name = "Counter" }]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]

[miniflare]
durable_objects_persist = true
